"""طبقة SEO تقنية عامة — robots.txt و sitemap و JSON-LD."""
from __future__ import annotations

import json
from datetime import date
from typing import Any
from xml.sax.saxutils import escape as xml_escape

from markupsafe import Markup
from sqlalchemy import select
from sqlalchemy.orm import Session

from modules.settings.service import get_public_base_url, get_setting
from modules.web_marketing.service import (
    SURFACE_HOTEL_PORTAL,
    SURFACE_RESTAURANT_SHOP,
    get_surface_admin_config,
)


def public_base_url(db: Session) -> str:
    try:
        from modules.seo.config import seo_config

        seo_base = (seo_config().get("public_base_url") or "").strip()
        if seo_base.startswith("http"):
            return seo_base.rstrip("/")
    except Exception:  # noqa: BLE001
        pass
    return get_public_base_url(db)


def _abs(base: str, path: str) -> str:
    p = (path or "/").strip() or "/"
    if not p.startswith("/"):
        p = "/" + p
    if base.startswith("http"):
        return f"{base.rstrip('/')}{p}"
    return p


def build_robots_txt(db: Session) -> str:
    base = public_base_url(db)
    shop = get_surface_admin_config(db, SURFACE_RESTAURANT_SHOP)
    hotel = get_surface_admin_config(db, SURFACE_HOTEL_PORTAL)
    lines = [
        "# Generated by Baytak web_marketing — technical SEO",
        "User-agent: *",
    ]
    # مسارات عامة صريحة (لا تغني عن المصادقة على الخاص)
    public_allows: list[str] = []
    if not (shop.get("robots") or "").startswith("noindex"):
        public_allows.extend(["/shop", "/offers", "/about"])
    else:
        lines.append("Disallow: /shop")
        lines.append("Disallow: /offers")
        lines.append("Disallow: /about")
    if not (hotel.get("robots") or "").startswith("noindex"):
        public_allows.extend(["/suites", "/stay"])
    else:
        lines.append("Disallow: /suites")
        lines.append("Disallow: /stay")
    for path in public_allows:
        lines.append(f"Allow: {path}")
    if not public_allows and not any(x.startswith("Disallow:") for x in lines):
        lines.append("Allow: /")

    # مناطق داخلية / تشغيل — لا تُفهرس
    for path in (
        "/admin",
        "/pos",
        "/api",
        "/auth",
        "/kitchen",
        "/kds",
        "/laundry",
        "/catalog",
        "/inventory",
        "/purchases",
        "/payments",
        "/customers",
        "/reports",
        "/gl",
        "/hr",
        "/messaging",
        "/backup",
        "/print",
        "/uploads/",
        "/static/uploads",
        "/docs",
        "/redoc",
        "/openapi.json",
    ):
        lines.append(f"Disallow: {path}")

    if base.startswith("http"):
        lines.append(f"Sitemap: {base}/sitemap.xml")
        lines.append(f"Sitemap: {base}/sitemap-products.xml")
        lines.append(f"Sitemap: {base}/sitemap-rooms.xml")
        lines.append(f"Sitemap: {base}/sitemap-images.xml")
    else:
        lines.append("Sitemap: /sitemap.xml")
    return "\n".join(lines) + "\n"


def _shop_indexable(db: Session) -> bool:
    shop = get_surface_admin_config(db, SURFACE_RESTAURANT_SHOP)
    return not (shop.get("robots") or "").startswith("noindex")


def _hotel_indexable(db: Session) -> bool:
    hotel = get_surface_admin_config(db, SURFACE_HOTEL_PORTAL)
    return not (hotel.get("robots") or "").startswith("noindex")


def _sitemap_urls(db: Session) -> list[tuple[str, str]]:
    """صفحات عامة قابلة للفهرسة فقط — بدون login/admin/API."""
    base = public_base_url(db)
    today = date.today().isoformat()
    urls: list[tuple[str, str]] = []
    if _shop_indexable(db):
        for path in ("/shop", "/offers", "/about"):
            urls.append((_abs(base, path), today))
    if _hotel_indexable(db):
        for path in ("/suites", "/stay"):
            urls.append((_abs(base, path), today))
        urls.extend(_room_urls(db, base, today))
    # إزالة التكرار مع الإبقاء على أول ظهور
    seen: set[str] = set()
    deduped: list[tuple[str, str]] = []
    for loc, lastmod in urls:
        if not loc.startswith("http") or loc in seen:
            continue
        seen.add(loc)
        deduped.append((loc, lastmod))
    return deduped


def _room_urls(db: Session, base: str, today: str) -> list[tuple[str, str]]:
    urls: list[tuple[str, str]] = []
    try:
        from modules.hotel.store_service import list_store_rooms, store_enabled

        if store_enabled(db):
            for card in list_store_rooms(db):
                room = getattr(card, "room", None)
                rid = getattr(room, "id", None) if room is not None else None
                if rid is None:
                    continue
                if hasattr(room, "seo_indexable") and room.seo_indexable is False:
                    continue
                urls.append((_abs(base, f"/suites/room/{int(rid)}"), today))
    except Exception:  # noqa: BLE001
        pass
    return urls


def _product_urls(db: Session, base: str, today: str) -> list[tuple[str, str]]:
    urls: list[tuple[str, str]] = []
    if not _shop_indexable(db):
        return urls
    try:
        from modules.catalog.models import Product

        products = db.scalars(
            select(Product).where(
                Product.is_active.is_(True),
                Product.show_in_shop.is_(True),
            )
        ).all()
        for p in products:
            if hasattr(p, "seo_indexable") and p.seo_indexable is False:
                continue
            urls.append((_abs(base, f"/shop?product={p.id}"), today))
    except Exception:  # noqa: BLE001
        pass
    return urls


def _image_urls(db: Session, base: str, today: str) -> list[tuple[str, str, str]]:
    """(loc, lastmod, image_loc)"""
    out: list[tuple[str, str, str]] = []
    try:
        from modules.catalog.models import Product

        for p in db.scalars(
            select(Product).where(
                Product.is_active.is_(True),
                Product.show_in_shop.is_(True),
                Product.image_filename.isnot(None),
            )
        ).all():
            img = _abs(base, f"/uploads/products/{p.image_filename}")
            page = _abs(base, f"/shop?product={p.id}")
            out.append((page, today, img))
    except Exception:  # noqa: BLE001
        pass
    try:
        from modules.hotel.models import HotelRoom

        for r in db.scalars(
            select(HotelRoom).where(
                HotelRoom.is_active.is_(True),
                HotelRoom.show_online.is_(True),
                HotelRoom.image_filename.isnot(None),
            )
        ).all():
            img = _abs(base, f"/uploads/hotel/{r.image_filename}")
            page = _abs(base, f"/suites/room/{r.id}")
            out.append((page, today, img))
    except Exception:  # noqa: BLE001
        pass
    return out


def _urlset_xml(urls: list[tuple[str, str]]) -> str:
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for loc, lastmod in urls:
        if not loc.startswith("http"):
            continue
        parts.append("  <url>")
        parts.append(f"    <loc>{xml_escape(loc)}</loc>")
        parts.append(f"    <lastmod>{xml_escape(lastmod)}</lastmod>")
        parts.append("  </url>")
    parts.append("</urlset>")
    return "\n".join(parts) + "\n"


def build_sitemap_xml(db: Session) -> str:
    return _urlset_xml(_sitemap_urls(db))


def build_sitemap_products_xml(db: Session) -> str:
    base = public_base_url(db)
    today = date.today().isoformat()
    return _urlset_xml(_product_urls(db, base, today))


def build_sitemap_rooms_xml(db: Session) -> str:
    base = public_base_url(db)
    today = date.today().isoformat()
    return _urlset_xml(_room_urls(db, base, today) if _hotel_indexable(db) else [])


def build_sitemap_images_xml(db: Session) -> str:
    base = public_base_url(db)
    today = date.today().isoformat()
    images = _image_urls(db, base, today)
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
        'xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
    ]
    for loc, lastmod, img in images:
        if not loc.startswith("http"):
            continue
        parts.append("  <url>")
        parts.append(f"    <loc>{xml_escape(loc)}</loc>")
        parts.append(f"    <lastmod>{xml_escape(lastmod)}</lastmod>")
        parts.append("    <image:image>")
        parts.append(f"      <image:loc>{xml_escape(img)}</image:loc>")
        parts.append("    </image:image>")
        parts.append("  </url>")
    parts.append("</urlset>")
    return "\n".join(parts) + "\n"


def _ld_script(data: Any) -> Markup:
    raw = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    safe = raw.replace("<", "\\u003c")
    return Markup(f'<script type="application/ld+json">{safe}</script>')


def build_json_ld(
    db: Session,
    surface: str,
    *,
    page_path: str = "/",
    page_title: str = "",
    page_description: str = "",
    breadcrumbs: list[tuple[str, str]] | None = None,
    faq: list[tuple[str, str]] | None = None,
    product: dict[str, Any] | None = None,
    entity_schema_json: str | None = None,
) -> Markup:
    """Schema.org — Hotel / Restaurant / Product / Breadcrumb / FAQ / Org."""
    base = public_base_url(db)
    if not base.startswith("http"):
        return Markup("")

    store_name = (get_setting(db, "store_name", "") or "").strip() or "Baytak"
    phone = (get_setting(db, "store_phone", "") or "").strip()
    desc = (page_description or "").strip()

    if surface == SURFACE_HOTEL_PORTAL:
        from modules.branding.service import hotel_display_name

        name = hotel_display_name(db) or store_name
        org_type = "Hotel"
        local_type = "LodgingBusiness"
    else:
        name = store_name
        org_type = "Restaurant"
        local_type = "Restaurant"

    blocks: list[dict[str, Any]] = []
    org: dict[str, Any] = {
        "@context": "https://schema.org",
        "@type": ["Organization", local_type, org_type],
        "name": name,
        "url": base,
    }
    if phone:
        org["telephone"] = phone
    # عنوان/إحداثيات — فقط إن وُجدت في الإعدادات (لا اختلاق)
    addr = (get_setting(db, "store_address", "") or "").strip()
    city = (get_setting(db, "store_city", "") or "").strip()
    if addr or city:
        postal: dict[str, Any] = {"@type": "PostalAddress", "addressCountry": "LY"}
        if addr:
            postal["streetAddress"] = addr
        if city:
            postal["addressLocality"] = city
        org["address"] = postal
    else:
        # TODO(Phase C+): أضف store_address / store_city في الإعدادات لدعم Local SEO
        pass
    blocks.append(org)

    page_node: dict[str, Any] = {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": page_title or name,
        "url": _abs(base, page_path or "/"),
        "inLanguage": "ar",
    }
    if desc:
        page_node["description"] = desc
    blocks.append(page_node)

    blocks.append(
        {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": name,
            "url": base,
            "inLanguage": "ar",
        }
    )

    if breadcrumbs:
        elements = []
        for i, (label, path) in enumerate(breadcrumbs, start=1):
            elements.append(
                {
                    "@type": "ListItem",
                    "position": i,
                    "name": label,
                    "item": _abs(base, path),
                }
            )
        blocks.append(
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": elements,
            }
        )

    if faq:
        blocks.append(
            {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": q,
                        "acceptedAnswer": {"@type": "Answer", "text": a},
                    }
                    for q, a in faq
                ],
            }
        )

    if product:
        prod: dict[str, Any] = {
            "@context": "https://schema.org",
            "@type": "Product",
            "name": product.get("name") or page_title,
            "url": _abs(base, page_path or "/"),
        }
        if product.get("description"):
            prod["description"] = product["description"]
        if product.get("image"):
            prod["image"] = product["image"]
        if product.get("price") is not None:
            prod["offers"] = {
                "@type": "Offer",
                "price": str(product["price"]),
                "priceCurrency": product.get("currency") or "LYD",
                "availability": "https://schema.org/InStock",
            }
        blocks.append(prod)

    if entity_schema_json:
        try:
            extra = json.loads(entity_schema_json)
            if isinstance(extra, list):
                blocks.extend([x for x in extra if isinstance(x, dict)])
            elif isinstance(extra, dict):
                blocks.append(extra)
        except json.JSONDecodeError:
            pass

    return _ld_script(blocks)
